### PR TITLE
Addressed audit feedback

### PR DESCRIPTION
**Pull request by pinebit**

### CODE REVIEW

**Comment by pinebit** [comment]
@Arachnid can I ask for some help on getting CI fixed?

**Comment by Arachnid** [comment]
Wow, this is a thoroughly bizarre issue. I don't think we use that repo anywhere. Master is still passing when I restart the build. I'm afraid I have no idea what could cause this.

**Comment by Arachnid** [comment]
Have you tried reverting the changes to package-lock.json?

**Comment by pinebit** [comment]
> Have you tried reverting the changes to package-lock.json?

Alright, the problem was that I used nodejs 16+, whereas this CI needed 10, and this messed up with package-lock.json.

**Review by Arachnid — APPROVED** [review]

**Pull request merged**
